export const projetos = [
  {
    titulo: "Dashboard Admin",
    descricao: "Painel completo com autenticação, gráficos e gerenciamento de usuários.",
    tecnologias: ["React", "Node.js", "Prisma"],
    imagem: "https://via.placeholder.com/400x200.png?text=Dashboard+Admin",
    github: "#",
    link: "#",
  },
  {
    titulo: "Clone Netflix",
    descricao: "App de streaming com integração da API TMDB e player de vídeo.",
    tecnologias: ["React", "Tailwind", "TMDB API"],
    imagem: "https://via.placeholder.com/400x200.png?text=Clone+Netflix",
    github: "#",
    link: "#",
  },
  {
    titulo: "Kanban Tasks",
    descricao: "Gerenciador de tarefas com sistema drag and drop estilo Trello.",
    tecnologias: ["React", "Zustand", "Express"],
    imagem: "https://via.placeholder.com/400x200.png?text=Kanban+Tasks",
    github: "#",
    link: "#",
  },
  {
    titulo: "Blog com Comentários",
    descricao: "Plataforma de publicação de artigos com autenticação e comentários.",
    tecnologias: ["Next.js", "Prisma", "JWT"],
    imagem: "https://via.placeholder.com/400x200.png?text=Blog",
    github: "#",
    link: "#",
  },
  {
    titulo: "Loja Virtual",
    descricao: "E-commerce com carrinho de compras, produtos e simulação de checkout.",
    tecnologias: ["React", "Styled Components", "FakeStore API"],
    imagem: "https://via.placeholder.com/400x200.png?text=E-commerce",
    github: "#",
    link: "#",
  },
  {
    titulo: "App de Finanças",
    descricao: "Controle de gastos com gráfico de entrada e saída de valores mensais.",
    tecnologias: ["React", "Chart.js", "Context API"],
    imagem: "https://via.placeholder.com/400x200.png?text=Finanças",
    github: "#",
    link: "#",
  },
];
